@startuml serial-echo-DTR

participant "serial-echo" as port0
participant "microAPRO-test" as port1

activate port0 #d982ff
activate port1 #d982ff

port1 o-> port0 : Change DTR pin, therefore changing the DCD/DSR and RT status.
port0 o-> port0 : Check if DSR/DCD has changed, change RT.
port0 o-> port1 : Change DTR pin, therefore changing DSR status.
port1 o-> port1 : Check if DSR has changed, change CD.
port1 o-> port0 : Repeat.

skinparam Shadowing false

skinparam ParticipantBackgroundColor 000
skinparam ParticipantFontColor fff
skinparam ParticipantFontSize 18
skinparam ParticipantBorderColor 000

skinparam ArrowColor 9308fa
skinparam ArrowFontColor 5100ba

@enduml
